# TCL File Generated by Component Editor 18.1
# Tue Dec 01 01:39:14 BRST 2020
# DO NOT MODIFY


# 
# acelerador_inlier "acelerador_inlier" v1.0
# Gustavo Mota 2020.12.01.01:39:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module acelerador_inlier
# 
set_module_property DESCRIPTION ""
set_module_property NAME acelerador_inlier
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MeusComponentes
set_module_property AUTHOR "Gustavo Mota"
set_module_property DISPLAY_NAME acelerador_inlier
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL inlier_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file inlier_checker.v VERILOG PATH inlier_checker.v
add_fileset_file inlier_function.v VERILOG PATH inlier_function.v
add_fileset_file inlier_interface.v VERILOG PATH inlier_interface.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL inlier_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file inlier_checker.v VERILOG PATH inlier_checker.v
add_fileset_file inlier_function.v VERILOG PATH inlier_function.v
add_fileset_file inlier_interface.v VERILOG PATH inlier_interface.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_escrita
# 
add_interface avalon_slave_escrita avalon end
set_interface_property avalon_slave_escrita addressUnits WORDS
set_interface_property avalon_slave_escrita associatedClock clock
set_interface_property avalon_slave_escrita associatedReset reset
set_interface_property avalon_slave_escrita bitsPerSymbol 8
set_interface_property avalon_slave_escrita burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_escrita burstcountUnits WORDS
set_interface_property avalon_slave_escrita explicitAddressSpan 0
set_interface_property avalon_slave_escrita holdTime 0
set_interface_property avalon_slave_escrita linewrapBursts false
set_interface_property avalon_slave_escrita maximumPendingReadTransactions 0
set_interface_property avalon_slave_escrita maximumPendingWriteTransactions 0
set_interface_property avalon_slave_escrita readLatency 0
set_interface_property avalon_slave_escrita readWaitTime 1
set_interface_property avalon_slave_escrita setupTime 0
set_interface_property avalon_slave_escrita timingUnits Cycles
set_interface_property avalon_slave_escrita writeWaitTime 0
set_interface_property avalon_slave_escrita ENABLED true
set_interface_property avalon_slave_escrita EXPORT_OF ""
set_interface_property avalon_slave_escrita PORT_NAME_MAP ""
set_interface_property avalon_slave_escrita CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_escrita SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_escrita write write Input 1
add_interface_port avalon_slave_escrita writedata writedata Input 32
set_interface_assignment avalon_slave_escrita embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_escrita embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_escrita embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_escrita embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_leitura
# 
add_interface avalon_slave_leitura avalon end
set_interface_property avalon_slave_leitura addressUnits WORDS
set_interface_property avalon_slave_leitura associatedClock clock
set_interface_property avalon_slave_leitura associatedReset reset
set_interface_property avalon_slave_leitura bitsPerSymbol 8
set_interface_property avalon_slave_leitura burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_leitura burstcountUnits WORDS
set_interface_property avalon_slave_leitura explicitAddressSpan 0
set_interface_property avalon_slave_leitura holdTime 0
set_interface_property avalon_slave_leitura linewrapBursts false
set_interface_property avalon_slave_leitura maximumPendingReadTransactions 0
set_interface_property avalon_slave_leitura maximumPendingWriteTransactions 0
set_interface_property avalon_slave_leitura readLatency 0
set_interface_property avalon_slave_leitura readWaitTime 1
set_interface_property avalon_slave_leitura setupTime 0
set_interface_property avalon_slave_leitura timingUnits Cycles
set_interface_property avalon_slave_leitura writeWaitTime 0
set_interface_property avalon_slave_leitura ENABLED true
set_interface_property avalon_slave_leitura EXPORT_OF ""
set_interface_property avalon_slave_leitura PORT_NAME_MAP ""
set_interface_property avalon_slave_leitura CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_leitura SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_leitura read read Input 1
add_interface_port avalon_slave_leitura readdata readdata Output 32
set_interface_assignment avalon_slave_leitura embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_leitura embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_leitura embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_leitura embeddedsw.configuration.isPrintableDevice 0

